/// \file
/// \ingroup tutorial_tree
///
/// Example of Root macro to copy a subset of a Tree to a new Tree, selecting entries.
///
/// Only selected entries are copied to the new Tree.
/// The input file has been generated by the program in $ROOTSYS/test/Event
/// with `Event 1000 1 99 1`
/// \macro_code
/// \author Rene Brun

#include "TBranch.h"
#include "TFile.h"
#include "TH2D.h"
#include "TTree.h"
#include "TString.h"
#include "TCanvas.h"

#include <iostream>




int skimtreeRun(float scaleF, TString infile) {


   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile(infile+".root");
   TTree *oldtree = (TTree*)oldfile->Get("tagVars/ttree");
   Long64_t nentries = oldtree->GetEntries();

   // Event *event   = 0;
   //  oldtree->SetBranchAddress("event",&event);
   // Declaration of leaf types
   Float_t         Jet_pt;
   //Float_t         Jet_genpt;
   Float_t         Jet_eta;
   // Float_t         Jet_phi;
   // Float_t         Jet_mass;
   Float_t         Jet_flavour;
   Float_t         Jet_nbHadrons;
   Float_t         Jet_ncHadrons;
   Float_t         Jet_JP;
   Float_t         Jet_JBP;
   Float_t         Jet_CSV;
   Float_t         Jet_CSVIVF;
   Float_t         Jet_cMVAv2;
   Float_t         Jet_SoftEl;
   Float_t         Jet_SoftMu;
   Float_t         TagVarCSV_jetNTracks;
   Float_t         TagVarCSV_jetNTracksEtaRel;
   Float_t         TagVarCSV_trackSumJetEtRatio;
   Float_t         TagVarCSV_trackSumJetDeltaR;
   Float_t         TagVarCSV_trackSip2dValAboveCharm;
   Float_t         TagVarCSV_trackSip2dSigAboveCharm;
   Float_t         TagVarCSV_trackSip3dValAboveCharm;
   Float_t         TagVarCSV_trackSip3dSigAboveCharm;
   Float_t         TagVarCSV_vertexCategory;
   Float_t         TagVarCSV_jetNSecondaryVertices;
   Float_t         TagVarCSV_vertexMass;
   Float_t         TagVarCSV_vertexNTracks;
   Float_t         TagVarCSV_vertexEnergyRatio;
   Float_t         TagVarCSV_vertexJetDeltaR;
   Float_t         TagVarCSV_flightDistance2dVal;
   Float_t         TagVarCSV_flightDistance2dSig;
   Float_t         TagVarCSV_flightDistance3dVal;
   Float_t         TagVarCSV_flightDistance3dSig;
   Float_t         TagVarCSV_trackSip2dSig_0;
   Float_t         TagVarCSV_trackSip2dSig_1;
   Float_t         TagVarCSV_trackSip2dSig_2;
   Float_t         TagVarCSV_trackSip2dSig_3;
   Float_t         TagVarCSV_trackSip3dSig_0;
   Float_t         TagVarCSV_trackSip3dSig_1;
   Float_t         TagVarCSV_trackSip3dSig_2;
   Float_t         TagVarCSV_trackSip3dSig_3;
   Float_t         TagVarCSV_trackPtRel_0;
   Float_t         TagVarCSV_trackPtRel_1;
   Float_t         TagVarCSV_trackPtRel_2;
   Float_t         TagVarCSV_trackPtRel_3;
   Float_t         TagVarCSV_trackDeltaR_0;
   Float_t         TagVarCSV_trackDeltaR_1;
   Float_t         TagVarCSV_trackDeltaR_2;
   Float_t         TagVarCSV_trackDeltaR_3;
   Float_t         TagVarCSV_trackPtRatio_0;
   Float_t         TagVarCSV_trackPtRatio_1;
   Float_t         TagVarCSV_trackPtRatio_2;
   Float_t         TagVarCSV_trackPtRatio_3;
   Float_t         TagVarCSV_trackJetDist_0;
   Float_t         TagVarCSV_trackJetDist_1;
   Float_t         TagVarCSV_trackJetDist_2;
   Float_t         TagVarCSV_trackJetDist_3;
   Float_t         TagVarCSV_trackDecayLenVal_0;
   Float_t         TagVarCSV_trackDecayLenVal_1;
   Float_t         TagVarCSV_trackDecayLenVal_2;
   Float_t         TagVarCSV_trackDecayLenVal_3;
   Float_t         TagVarCSV_trackEtaRel_0;
   Float_t         TagVarCSV_trackEtaRel_1;
   Float_t         TagVarCSV_trackEtaRel_2;
   Float_t         TagVarCSV_trackEtaRel_3;
   Float_t         TagVarCSV_trackSip2dSig_4;
   Float_t         TagVarCSV_trackSip2dSig_5;
   Float_t         TagVarCSV_trackSip2dSig_6;
   Float_t         TagVarCSV_trackSip2dSig_7;
   Float_t         TagVarCSV_trackSip3dSig_4;
   Float_t         TagVarCSV_trackSip3dSig_5;
   Float_t         TagVarCSV_trackSip3dSig_6;
   Float_t         TagVarCSV_trackSip3dSig_7;
   Float_t         TagVarCSV_trackPtRel_4;
   Float_t         TagVarCSV_trackPtRel_5;
   Float_t         TagVarCSV_trackPtRel_6;
   Float_t         TagVarCSV_trackPtRel_7;
   Float_t         TagVarCSV_trackDeltaR_4;
   Float_t         TagVarCSV_trackDeltaR_5;
   Float_t         TagVarCSV_trackDeltaR_6;
   Float_t         TagVarCSV_trackDeltaR_7;
   Float_t         TagVarCSV_trackPtRatio_4;
   Float_t         TagVarCSV_trackPtRatio_5;
   Float_t         TagVarCSV_trackPtRatio_6;
   Float_t         TagVarCSV_trackPtRatio_7;
   Float_t         TagVarCSV_trackJetDist_4;
   Float_t         TagVarCSV_trackJetDist_5;
   Float_t         TagVarCSV_trackJetDist_6;
   Float_t         TagVarCSV_trackJetDist_7;
   Float_t         TagVarCSV_trackDecayLenVal_4;
   Float_t         TagVarCSV_trackDecayLenVal_5;
   Float_t         TagVarCSV_trackDecayLenVal_6;
   Float_t         TagVarCSV_trackDecayLenVal_7;
   Float_t         TagVarCSV_trackEtaRel_4;
   Float_t         TagVarCSV_trackEtaRel_5;
   Float_t         TagVarCSV_trackEtaRel_6;
   Float_t         TagVarCSV_trackEtaRel_7;

   // List of branches
   TBranch        *b_Jet_pt;   //!
   // TBranch        *b_Jet_genpt;   //!
   TBranch        *b_Jet_eta;   //!
   //  TBranch        *b_Jet_phi;   //!
   //  TBranch        *b_Jet_mass;   //!
   TBranch        *b_Jet_flavour;   //!
   TBranch        *b_Jet_nbHadrons;   //!
   TBranch        *b_Jet_ncHadrons;   //!
   TBranch        *b_Jet_JP;   //!
   TBranch        *b_Jet_JBP;   //!
   TBranch        *b_Jet_CSV;   //!
   TBranch        *b_Jet_CSVIVF;   //!
   TBranch        *b_Jet_cMVAv2;   //!
   TBranch        *b_Jet_SoftEl;   //!
   TBranch        *b_Jet_SoftMu;   //!
   TBranch        *b_TagVarCSV_jetNTracks;   //!
   TBranch        *b_TagVarCSV_jetNTracksEtaRel;   //!
   TBranch        *b_TagVarCSV_trackSumJetEtRatio;   //!
   TBranch        *b_TagVarCSV_trackSumJetDeltaR;   //!
   TBranch        *b_TagVarCSV_trackSip2dValAboveCharm;   //!
   TBranch        *b_TagVarCSV_trackSip2dSigAboveCharm;   //!
   TBranch        *b_TagVarCSV_trackSip3dValAboveCharm;   //!
   TBranch        *b_TagVarCSV_trackSip3dSigAboveCharm;   //!
   TBranch        *b_TagVarCSV_vertexCategory;   //!
   TBranch        *b_TagVarCSV_jetNSecondaryVertices;   //!
   TBranch        *b_TagVarCSV_vertexMass;   //!
   TBranch        *b_TagVarCSV_vertexNTracks;   //!
   TBranch        *b_TagVarCSV_vertexEnergyRatio;   //!
   TBranch        *b_TagVarCSV_vertexJetDeltaR;   //!
   TBranch        *b_TagVarCSV_flightDistance2dVal;   //!
   TBranch        *b_TagVarCSV_flightDistance2dSig;   //!
   TBranch        *b_TagVarCSV_flightDistance3dVal;   //!
   TBranch        *b_TagVarCSV_flightDistance3dSig;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_0;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_1;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_2;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_3;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_0;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_1;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_2;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_3;   //!
   TBranch        *b_TagVarCSV_trackPtRel_0;   //!
   TBranch        *b_TagVarCSV_trackPtRel_1;   //!
   TBranch        *b_TagVarCSV_trackPtRel_2;   //!
   TBranch        *b_TagVarCSV_trackPtRel_3;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_0;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_1;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_2;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_3;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_0;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_1;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_2;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_3;   //!
   TBranch        *b_TagVarCSV_trackJetDist_0;   //!
   TBranch        *b_TagVarCSV_trackJetDist_1;   //!
   TBranch        *b_TagVarCSV_trackJetDist_2;   //!
   TBranch        *b_TagVarCSV_trackJetDist_3;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_0;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_1;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_2;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_3;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_0;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_1;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_2;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_3;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_4;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_5;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_6;   //!
   TBranch        *b_TagVarCSV_trackSip2dSig_7;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_4;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_5;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_6;   //!
   TBranch        *b_TagVarCSV_trackSip3dSig_7;   //!
   TBranch        *b_TagVarCSV_trackPtRel_4;   //!
   TBranch        *b_TagVarCSV_trackPtRel_5;   //!
   TBranch        *b_TagVarCSV_trackPtRel_6;   //!
   TBranch        *b_TagVarCSV_trackPtRel_7;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_4;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_5;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_6;   //!
   TBranch        *b_TagVarCSV_trackDeltaR_7;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_4;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_5;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_6;   //!
   TBranch        *b_TagVarCSV_trackPtRatio_7;   //!
   TBranch        *b_TagVarCSV_trackJetDist_4;   //!
   TBranch        *b_TagVarCSV_trackJetDist_5;   //!
   TBranch        *b_TagVarCSV_trackJetDist_6;   //!
   TBranch        *b_TagVarCSV_trackJetDist_7;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_4;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_5;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_6;   //!
   TBranch        *b_TagVarCSV_trackDecayLenVal_7;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_4;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_5;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_6;   //!
   TBranch        *b_TagVarCSV_trackEtaRel_7;   //!

   oldtree->SetBranchAddress("Jet_pt", &Jet_pt, &b_Jet_pt);
   // oldtree->SetBranchAddress("Jet_genpt", &Jet_genpt, &b_Jet_genpt);
   oldtree->SetBranchAddress("Jet_eta", &Jet_eta, &b_Jet_eta);
   //   oldtree->SetBranchAddress("Jet_phi", &Jet_phi, &b_Jet_phi);
   //   oldtree->SetBranchAddress("Jet_mass", &Jet_mass, &b_Jet_mass);
   oldtree->SetBranchAddress("Jet_flavour", &Jet_flavour, &b_Jet_flavour);
   oldtree->SetBranchAddress("Jet_nbHadrons", &Jet_nbHadrons, &b_Jet_nbHadrons);
   oldtree->SetBranchAddress("Jet_ncHadrons", &Jet_ncHadrons, &b_Jet_ncHadrons);
   oldtree->SetBranchAddress("Jet_JP", &Jet_JP, &b_Jet_JP);
   oldtree->SetBranchAddress("Jet_JBP", &Jet_JBP, &b_Jet_JBP);
   oldtree->SetBranchAddress("Jet_CSV", &Jet_CSV, &b_Jet_CSV);
   oldtree->SetBranchAddress("Jet_CSVIVF", &Jet_CSVIVF, &b_Jet_CSVIVF);
   oldtree->SetBranchAddress("Jet_cMVAv2", &Jet_cMVAv2, &b_Jet_cMVAv2);
   oldtree->SetBranchAddress("Jet_SoftEl", &Jet_SoftEl, &b_Jet_SoftEl);
   oldtree->SetBranchAddress("Jet_SoftMu", &Jet_SoftMu, &b_Jet_SoftMu);
   oldtree->SetBranchAddress("TagVarCSV_jetNTracks", &TagVarCSV_jetNTracks, &b_TagVarCSV_jetNTracks);
   oldtree->SetBranchAddress("TagVarCSV_jetNTracksEtaRel", &TagVarCSV_jetNTracksEtaRel, &b_TagVarCSV_jetNTracksEtaRel);
   oldtree->SetBranchAddress("TagVarCSV_trackSumJetEtRatio", &TagVarCSV_trackSumJetEtRatio, &b_TagVarCSV_trackSumJetEtRatio);
   oldtree->SetBranchAddress("TagVarCSV_trackSumJetDeltaR", &TagVarCSV_trackSumJetDeltaR, &b_TagVarCSV_trackSumJetDeltaR);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dValAboveCharm", &TagVarCSV_trackSip2dValAboveCharm, &b_TagVarCSV_trackSip2dValAboveCharm);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSigAboveCharm", &TagVarCSV_trackSip2dSigAboveCharm, &b_TagVarCSV_trackSip2dSigAboveCharm);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dValAboveCharm", &TagVarCSV_trackSip3dValAboveCharm, &b_TagVarCSV_trackSip3dValAboveCharm);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSigAboveCharm", &TagVarCSV_trackSip3dSigAboveCharm, &b_TagVarCSV_trackSip3dSigAboveCharm);
   oldtree->SetBranchAddress("TagVarCSV_vertexCategory", &TagVarCSV_vertexCategory, &b_TagVarCSV_vertexCategory);
   oldtree->SetBranchAddress("TagVarCSV_jetNSecondaryVertices", &TagVarCSV_jetNSecondaryVertices, &b_TagVarCSV_jetNSecondaryVertices);
   oldtree->SetBranchAddress("TagVarCSV_vertexMass", &TagVarCSV_vertexMass, &b_TagVarCSV_vertexMass);
   oldtree->SetBranchAddress("TagVarCSV_vertexNTracks", &TagVarCSV_vertexNTracks, &b_TagVarCSV_vertexNTracks);
   oldtree->SetBranchAddress("TagVarCSV_vertexEnergyRatio", &TagVarCSV_vertexEnergyRatio, &b_TagVarCSV_vertexEnergyRatio);
   oldtree->SetBranchAddress("TagVarCSV_vertexJetDeltaR", &TagVarCSV_vertexJetDeltaR, &b_TagVarCSV_vertexJetDeltaR);
   oldtree->SetBranchAddress("TagVarCSV_flightDistance2dVal", &TagVarCSV_flightDistance2dVal, &b_TagVarCSV_flightDistance2dVal);
   oldtree->SetBranchAddress("TagVarCSV_flightDistance2dSig", &TagVarCSV_flightDistance2dSig, &b_TagVarCSV_flightDistance2dSig);
   oldtree->SetBranchAddress("TagVarCSV_flightDistance3dVal", &TagVarCSV_flightDistance3dVal, &b_TagVarCSV_flightDistance3dVal);
   oldtree->SetBranchAddress("TagVarCSV_flightDistance3dSig", &TagVarCSV_flightDistance3dSig, &b_TagVarCSV_flightDistance3dSig);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_0", &TagVarCSV_trackSip2dSig_0, &b_TagVarCSV_trackSip2dSig_0);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_1", &TagVarCSV_trackSip2dSig_1, &b_TagVarCSV_trackSip2dSig_1);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_2", &TagVarCSV_trackSip2dSig_2, &b_TagVarCSV_trackSip2dSig_2);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_3", &TagVarCSV_trackSip2dSig_3, &b_TagVarCSV_trackSip2dSig_3);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_0", &TagVarCSV_trackSip3dSig_0, &b_TagVarCSV_trackSip3dSig_0);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_1", &TagVarCSV_trackSip3dSig_1, &b_TagVarCSV_trackSip3dSig_1);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_2", &TagVarCSV_trackSip3dSig_2, &b_TagVarCSV_trackSip3dSig_2);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_3", &TagVarCSV_trackSip3dSig_3, &b_TagVarCSV_trackSip3dSig_3);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_0", &TagVarCSV_trackPtRel_0, &b_TagVarCSV_trackPtRel_0);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_1", &TagVarCSV_trackPtRel_1, &b_TagVarCSV_trackPtRel_1);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_2", &TagVarCSV_trackPtRel_2, &b_TagVarCSV_trackPtRel_2);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_3", &TagVarCSV_trackPtRel_3, &b_TagVarCSV_trackPtRel_3);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_0", &TagVarCSV_trackDeltaR_0, &b_TagVarCSV_trackDeltaR_0);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_1", &TagVarCSV_trackDeltaR_1, &b_TagVarCSV_trackDeltaR_1);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_2", &TagVarCSV_trackDeltaR_2, &b_TagVarCSV_trackDeltaR_2);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_3", &TagVarCSV_trackDeltaR_3, &b_TagVarCSV_trackDeltaR_3);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_0", &TagVarCSV_trackPtRatio_0, &b_TagVarCSV_trackPtRatio_0);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_1", &TagVarCSV_trackPtRatio_1, &b_TagVarCSV_trackPtRatio_1);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_2", &TagVarCSV_trackPtRatio_2, &b_TagVarCSV_trackPtRatio_2);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_3", &TagVarCSV_trackPtRatio_3, &b_TagVarCSV_trackPtRatio_3);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_0", &TagVarCSV_trackJetDist_0, &b_TagVarCSV_trackJetDist_0);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_1", &TagVarCSV_trackJetDist_1, &b_TagVarCSV_trackJetDist_1);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_2", &TagVarCSV_trackJetDist_2, &b_TagVarCSV_trackJetDist_2);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_3", &TagVarCSV_trackJetDist_3, &b_TagVarCSV_trackJetDist_3);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_0", &TagVarCSV_trackDecayLenVal_0, &b_TagVarCSV_trackDecayLenVal_0);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_1", &TagVarCSV_trackDecayLenVal_1, &b_TagVarCSV_trackDecayLenVal_1);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_2", &TagVarCSV_trackDecayLenVal_2, &b_TagVarCSV_trackDecayLenVal_2);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_3", &TagVarCSV_trackDecayLenVal_3, &b_TagVarCSV_trackDecayLenVal_3);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_0", &TagVarCSV_trackEtaRel_0, &b_TagVarCSV_trackEtaRel_0);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_1", &TagVarCSV_trackEtaRel_1, &b_TagVarCSV_trackEtaRel_1);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_2", &TagVarCSV_trackEtaRel_2, &b_TagVarCSV_trackEtaRel_2);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_3", &TagVarCSV_trackEtaRel_3, &b_TagVarCSV_trackEtaRel_3);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_4", &TagVarCSV_trackSip2dSig_4, &b_TagVarCSV_trackSip2dSig_4);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_5", &TagVarCSV_trackSip2dSig_5, &b_TagVarCSV_trackSip2dSig_5);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_6", &TagVarCSV_trackSip2dSig_6, &b_TagVarCSV_trackSip2dSig_6);
   oldtree->SetBranchAddress("TagVarCSV_trackSip2dSig_7", &TagVarCSV_trackSip2dSig_7, &b_TagVarCSV_trackSip2dSig_7);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_4", &TagVarCSV_trackSip3dSig_4, &b_TagVarCSV_trackSip3dSig_4);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_5", &TagVarCSV_trackSip3dSig_5, &b_TagVarCSV_trackSip3dSig_5);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_6", &TagVarCSV_trackSip3dSig_6, &b_TagVarCSV_trackSip3dSig_6);
   oldtree->SetBranchAddress("TagVarCSV_trackSip3dSig_7", &TagVarCSV_trackSip3dSig_7, &b_TagVarCSV_trackSip3dSig_7);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_4", &TagVarCSV_trackPtRel_4, &b_TagVarCSV_trackPtRel_4);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_5", &TagVarCSV_trackPtRel_5, &b_TagVarCSV_trackPtRel_5);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_6", &TagVarCSV_trackPtRel_6, &b_TagVarCSV_trackPtRel_6);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRel_7", &TagVarCSV_trackPtRel_7, &b_TagVarCSV_trackPtRel_7);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_4", &TagVarCSV_trackDeltaR_4, &b_TagVarCSV_trackDeltaR_4);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_5", &TagVarCSV_trackDeltaR_5, &b_TagVarCSV_trackDeltaR_5);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_6", &TagVarCSV_trackDeltaR_6, &b_TagVarCSV_trackDeltaR_6);
   oldtree->SetBranchAddress("TagVarCSV_trackDeltaR_7", &TagVarCSV_trackDeltaR_7, &b_TagVarCSV_trackDeltaR_7);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_4", &TagVarCSV_trackPtRatio_4, &b_TagVarCSV_trackPtRatio_4);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_5", &TagVarCSV_trackPtRatio_5, &b_TagVarCSV_trackPtRatio_5);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_6", &TagVarCSV_trackPtRatio_6, &b_TagVarCSV_trackPtRatio_6);
   oldtree->SetBranchAddress("TagVarCSV_trackPtRatio_7", &TagVarCSV_trackPtRatio_7, &b_TagVarCSV_trackPtRatio_7);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_4", &TagVarCSV_trackJetDist_4, &b_TagVarCSV_trackJetDist_4);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_5", &TagVarCSV_trackJetDist_5, &b_TagVarCSV_trackJetDist_5);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_6", &TagVarCSV_trackJetDist_6, &b_TagVarCSV_trackJetDist_6);
   oldtree->SetBranchAddress("TagVarCSV_trackJetDist_7", &TagVarCSV_trackJetDist_7, &b_TagVarCSV_trackJetDist_7);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_4", &TagVarCSV_trackDecayLenVal_4, &b_TagVarCSV_trackDecayLenVal_4);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_5", &TagVarCSV_trackDecayLenVal_5, &b_TagVarCSV_trackDecayLenVal_5);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_6", &TagVarCSV_trackDecayLenVal_6, &b_TagVarCSV_trackDecayLenVal_6);
   oldtree->SetBranchAddress("TagVarCSV_trackDecayLenVal_7", &TagVarCSV_trackDecayLenVal_7, &b_TagVarCSV_trackDecayLenVal_7);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_4", &TagVarCSV_trackEtaRel_4, &b_TagVarCSV_trackEtaRel_4);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_5", &TagVarCSV_trackEtaRel_5, &b_TagVarCSV_trackEtaRel_5);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_6", &TagVarCSV_trackEtaRel_6, &b_TagVarCSV_trackEtaRel_6);
   oldtree->SetBranchAddress("TagVarCSV_trackEtaRel_7", &TagVarCSV_trackEtaRel_7, &b_TagVarCSV_trackEtaRel_7);


   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile(infile+"_small.root","recreate");
   TTree *newtree = oldtree->CloneTree(0);
   TH2D* thisshape  =  new TH2D("thisPtEta",";#eta;P_{T}", 6,0,2.4,14,30,100);
   TFile *refPTEtaFile = new TFile("all_PTETA.root","read");

   TH2D* refPTEta  = (TH2D*)refPTEtaFile->Get("PtEta");
 
   //  for (Long64_t j=0;j<100; j++){
   //  cout << "number of iterations on sample" << j <<endl; 
   //  cout << "events picked: "<< thisshape->GetEntries()<< " events missing " << thisshape->GetEntries()-scaleF*refPTEta->GetEntries()<<endl;
     for (Long64_t i=0;i<nentries; i++) {

       oldtree->GetEntry(i);
       //cout << "number of iterations on sample" << i <<endl; 
       // i = i+99; 
       //  cout << i << " " << j<< endl;
       //    if(Jet_nbHadrons>1 ) continue;
       if(i%10000==1)  cout << i << " out of " << nentries<< " PT "<< Jet_pt  << endl;
       float binX = thisshape->GetXaxis()->FindBin(fabs(Jet_eta));
       float binY= thisshape->GetYaxis()->FindBin(Jet_pt);
       if (thisshape->GetBinContent(binX,binY)>scaleF*50000.) continue;
       // if (thisshape->GetBinContent(binX,binY)>scaleF*30000.&&Jet_pt>70&&fabs(Jet_eta)>1.6) continue;
       /* if(thisshape->GetBinContent(binX,binY)>scaleF*refPTEta->GetBinContent(binX,binY)) {
	 // cout << binX << " "<< binY << " eta "<<  fabs(Jet_eta) << " pt "<<Jet_pt <<endl ;
	 // cout << thisshape->GetBinContent(binX,binY) << " "<< refPTEta->GetBinContent(binX,binY)<<endl;
	 // cout <<  " starts throuing away"<<endl; 
	 continue;
	 }*/
       thisshape->Fill(fabs(Jet_eta),Jet_pt);
       newtree->Fill();
       
       // if (thisshape->GetEntries()>0.995*scaleF*refPTEta->GetEntries()) break;
    }
     //}
   TCanvas* can = new TCanvas("check");
   // thisshape->Divide(refPTEta);
   thisshape->Draw("colz");
   // newfile-Write();
   newtree->Print();
   newtree->AutoSave();
   newfile->Write();
   delete oldfile;
   delete newfile;
   return 0;
}
void skimtree() {
    
   skimtreeRun(1., TString("QCDu") );
   skimtreeRun(0.2, TString("QCDc") );
   skimtreeRun(0.1, TString("QCDb") );
  //  skimtreeRun(0.2, TString("allbb") );
  // skimtreeRun(0.1, TString("allcc") );
  
  //  skimtreeRun(10., TString("JetTaggingVariables") );
}
